# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

before_install:
  - Rscript -e 'install.packages("Rdpack")'

env:
  - NOT_CRAN=true

os:
- linux

r:
 - release
 - devel

r_packages:
  - covr

after_success:
- travis_wait 45 Rscript -e 'covr::codecov(quiet = FALSE, type = "tests")'
